# Generated by Django 6.0.9 on 2026-10-08 09:37

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('requested_url', models.URLField(max_length=2048, verbose_name='requested URL')),
                ('final_url', models.URLField(blank=True, max_length=2048, verbose_name='final URL')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Fetched'), ('refused', 'Refused as unsafe'), ('failed', 'Fetch failed')], default='pending', max_length=16, verbose_name='status')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='content type')),
                ('error_reason', models.CharField(blank=True, max_length=255, verbose_name='error reason')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='meta description')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='language')),
                ('canonical_url', models.URLField(blank=True, max_length=2048, verbose_name='canonical URL')),
                ('headings', models.JSONField(blank=True, default=list, verbose_name='headings')),
                ('text', models.TextField(blank=True, verbose_name='extracted text')),
                ('internal_links', models.JSONField(blank=True, default=list, verbose_name='internal links')),
                ('social_links', models.JSONField(blank=True, default=list, verbose_name='social links')),
                ('emails', models.JSONField(blank=True, default=list, verbose_name='public emails')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='content hash')),
                ('resolved_ips', models.JSONField(blank=True, default=list, verbose_name='resolved IPs')),
                ('truncated', models.BooleanField(default=False, verbose_name='truncated')),
                ('elapsed_ms', models.FloatField(blank=True, null=True, verbose_name='elapsed ms')),
                ('fetched_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fetched at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'website snapshot',
                'verbose_name_plural': 'website snapshots',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'requested_url', '-created_at'], name='snapshot_org_url_idx'), models.Index(fields=['organization', 'status'], name='snapshot_org_status_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
