# Generated by Django 6.0.9 on 2026-10-08 14:20

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('website', models.URLField(blank=True, max_length=2048, verbose_name='website')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='company name')),
                ('one_line_summary', models.TextField(blank=True, verbose_name='one-line summary')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='industry')),
                ('business_model', models.CharField(blank=True, max_length=200, verbose_name='business model')),
                ('value_proposition', models.TextField(blank=True, verbose_name='value proposition')),
                ('pricing_summary', models.TextField(blank=True, verbose_name='pricing')),
                ('products', models.JSONField(blank=True, default=list, verbose_name='products')),
                ('target_customers', models.JSONField(blank=True, default=list, verbose_name='target customers')),
                ('use_cases', models.JSONField(blank=True, default=list, verbose_name='use cases')),
                ('pain_points_solved', models.JSONField(blank=True, default=list, verbose_name='pain points solved')),
                ('geographies', models.JSONField(blank=True, default=list, verbose_name='geographies')),
                ('buyer_personas', models.JSONField(blank=True, default=list, verbose_name='buyer personas')),
                ('competitors', models.JSONField(blank=True, default=list, verbose_name='competitors')),
                ('evidence', models.JSONField(blank=True, default=list, verbose_name='evidence')),
                ('unknowns', models.JSONField(blank=True, default=list, verbose_name='unknowns')),
                ('confidence', models.CharField(blank=True, max_length=10, verbose_name='confidence')),
                ('ai_values', models.JSONField(blank=True, default=dict, verbose_name='AI values')),
                ('edited_fields', models.JSONField(blank=True, default=list, verbose_name='human-edited fields')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('ready', 'Ready for review'), ('confirmed', 'Confirmed by the customer'), ('failed', 'Analysis failed')], default='draft', max_length=16, verbose_name='status')),
                ('analysis_error', models.CharField(blank=True, max_length=255, verbose_name='analysis error')),
                ('prompt_pin', models.CharField(blank=True, max_length=100, verbose_name='prompt version')),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='last analyzed at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('source_snapshots', models.ManyToManyField(blank=True, related_name='company_profiles', to='intelligence.websitesnapshot', verbose_name='source snapshots')),
            ],
            options={
                'verbose_name': 'company profile',
                'verbose_name_plural': 'company profiles',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('organization',), name='one_company_profile_per_organization')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
