# Generated by Django 6.0.9 on 2026-10-08 19:17

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_companyprofile'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ai_values', models.JSONField(blank=True, default=dict, verbose_name='AI values')),
                ('edited_fields', models.JSONField(blank=True, default=list, verbose_name='human-edited fields')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='name')),
                ('industries', models.JSONField(blank=True, default=list, verbose_name='industries')),
                ('countries', models.JSONField(blank=True, default=list, verbose_name='countries')),
                ('employee_range', models.CharField(blank=True, max_length=60, verbose_name='employee range')),
                ('business_size', models.CharField(blank=True, max_length=60, verbose_name='estimated business size')),
                ('business_models', models.JSONField(blank=True, default=list, verbose_name='business models')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name='technologies')),
                ('growth_stage', models.CharField(blank=True, max_length=60, verbose_name='growth stage')),
                ('job_titles', models.JSONField(blank=True, default=list, verbose_name='job titles')),
                ('departments', models.JSONField(blank=True, default=list, verbose_name='departments')),
                ('seniority', models.JSONField(blank=True, default=list, verbose_name='seniority')),
                ('responsibilities', models.JSONField(blank=True, default=list, verbose_name='responsibilities')),
                ('pain_signals', models.JSONField(blank=True, default=list, verbose_name='pain signals')),
                ('rationale', models.TextField(blank=True, verbose_name='rationale')),
                ('evidence', models.JSONField(blank=True, default=list, verbose_name='evidence')),
                ('confidence', models.CharField(blank=True, max_length=10, verbose_name='confidence')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready for review'), ('active', 'Active'), ('failed', 'Generation failed')], default='draft', max_length=16, verbose_name='status')),
                ('generation_error', models.CharField(blank=True, max_length=255, verbose_name='generation error')),
                ('prompt_pin', models.CharField(blank=True, max_length=100, verbose_name='prompt version')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('source_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icps', to='intelligence.companyprofile', verbose_name='generated from')),
            ],
            options={
                'verbose_name': 'ideal customer profile',
                'verbose_name_plural': 'ideal customer profiles',
                'ordering': ['-is_active', '-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='icp_org_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization',), name='one_active_icp_per_organization')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
