# Generated by Django 6.0.9 on 2026-10-09 08:59

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_icp'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='ISO 3166-1 alpha-2 code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('region', models.CharField(blank=True, max_length=60, verbose_name='region')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='languages')),
                ('timezones', models.JSONField(blank=True, default=list, verbose_name='timezones')),
                ('major_industries', models.JSONField(blank=True, default=list, verbose_name='major industries')),
                ('business_hubs', models.JSONField(blank=True, default=list, verbose_name='business hubs')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='channel preference')),
                ('communication_notes', models.TextField(blank=True, verbose_name='communication notes')),
                ('data_protection_law', models.CharField(blank=True, max_length=200, verbose_name='data protection law')),
                ('regulatory_notes', models.TextField(blank=True, verbose_name='regulatory notes')),
                ('is_launch_market', models.BooleanField(default=False, verbose_name='launch market')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'country profile',
                'verbose_name_plural': 'country profiles',
                'ordering': ['-is_launch_market', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fit', models.CharField(choices=[('high', 'High fit'), ('medium_high', 'Medium-high fit'), ('medium', 'Medium fit'), ('low', 'Low fit')], max_length=16, verbose_name='fit')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='score')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='rank')),
                ('reasoning', models.TextField(verbose_name='reasoning')),
                ('factors', models.JSONField(blank=True, default=dict, verbose_name='factors')),
                ('recommended_channels', models.JSONField(blank=True, default=list, verbose_name='recommended channels')),
                ('cautions', models.JSONField(blank=True, default=list, verbose_name='cautions')),
                ('is_selected', models.BooleanField(default=False, verbose_name='selected by the customer')),
                ('prompt_pin', models.CharField(blank=True, max_length=100, verbose_name='prompt version')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='intelligence.countryprofile', verbose_name='country')),
                ('icp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_recommendations', to='intelligence.icp', verbose_name='generated for')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'market recommendation',
                'verbose_name_plural': 'market recommendations',
                'ordering': ['rank', '-score'],
                'indexes': [models.Index(fields=['organization', '-score'], name='market_org_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'country'), name='one_recommendation_per_country_per_org')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
