# Generated by Django 6.0.9 on 2026-10-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_leadsignal'),
        ('intelligence', '0004_countryprofile_marketrecommendation'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesnapshot',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='companies.company', verbose_name='company'),
        ),
        migrations.AddIndex(
            model_name='websitesnapshot',
            index=models.Index(fields=['company', 'requested_url', '-fetched_at'], name='snapshot_company_page_idx'),
        ),
    ]
