# Generated by Django 6.0.9 on 2026-10-09 19:28

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_leadsignal'),
        ('intelligence', '0005_websitesnapshot_company_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ai_values', models.JSONField(blank=True, default=dict, verbose_name='AI values')),
                ('edited_fields', models.JSONField(blank=True, default=list, verbose_name='human-edited fields')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('why_they_may_buy', models.JSONField(blank=True, default=list, verbose_name='why they may buy')),
                ('likely_pain', models.JSONField(blank=True, default=list, verbose_name='likely pain')),
                ('possible_use_case', models.TextField(blank=True, verbose_name='possible use case')),
                ('suggested_approach', models.TextField(blank=True, verbose_name='suggested approach')),
                ('personalization_points', models.JSONField(blank=True, default=list, verbose_name='personalization points')),
                ('decision_maker_titles', models.JSONField(blank=True, default=list, verbose_name='decision maker titles')),
                ('reason_observation', models.CharField(blank=True, max_length=300, verbose_name='observation')),
                ('reason_implication', models.CharField(blank=True, max_length=300, verbose_name='implication')),
                ('reason_evidence', models.JSONField(blank=True, default=list, verbose_name='reason evidence')),
                ('reason_confidence', models.CharField(blank=True, max_length=10, verbose_name='reason confidence')),
                ('reason_rejected', models.CharField(blank=True, max_length=255, verbose_name='reason rejected because')),
                ('evidence', models.JSONField(blank=True, default=list, verbose_name='evidence')),
                ('unknowns', models.JSONField(blank=True, default=list, verbose_name='unknowns')),
                ('confidence', models.CharField(blank=True, max_length=10, verbose_name='confidence')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('researching', 'Researching'), ('ready', 'Ready'), ('failed', 'Research failed')], default='pending', max_length=16, verbose_name='status')),
                ('research_error', models.CharField(blank=True, max_length=255, verbose_name='error')),
                ('prompt_pin', models.CharField(blank=True, max_length=100, verbose_name='prompt version')),
                ('researched_at', models.DateTimeField(blank=True, null=True, verbose_name='researched at')),
                ('score_at_research', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='score when researched')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='companies.company', verbose_name='company')),
                ('icp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research', to='intelligence.icp', verbose_name='ICP')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('source_signals', models.ManyToManyField(blank=True, related_name='research', to='companies.leadsignal', verbose_name='source signals')),
                ('source_snapshots', models.ManyToManyField(blank=True, related_name='research', to='intelligence.websitesnapshot', verbose_name='source snapshots')),
            ],
            options={
                'verbose_name': 'prospect research',
                'verbose_name_plural': 'prospect research',
                'ordering': ['-researched_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status', '-researched_at'], name='research_org_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'icp'), name='one_research_per_company_per_icp')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
