# Generated by Django 6.0.9 on 2026-10-10 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_prospectresearch'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('url', models.URLField(db_index=True, max_length=2048, verbose_name='URL')),
                ('final_url', models.URLField(blank=True, max_length=2048, verbose_name='final URL')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='domain')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Could not be completed')], default='pending', max_length=16, verbose_name='status')),
                ('error_reason', models.CharField(blank=True, max_length=255, verbose_name='error')),
                ('overall_score', models.PositiveSmallIntegerField(default=0, verbose_name='overall score')),
                ('scores', models.JSONField(blank=True, default=dict, verbose_name='scores')),
                ('checks', models.JSONField(blank=True, default=list, verbose_name='checks')),
                ('performance', models.JSONField(blank=True, default=list, verbose_name='performance observations')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='recommendations')),
                ('notes', models.JSONField(blank=True, default=dict, verbose_name='notes per dimension')),
                ('what_they_sell', models.CharField(blank=True, max_length=300, verbose_name='what they sell')),
                ('who_its_for', models.CharField(blank=True, max_length=300, verbose_name='who it is for')),
                ('confidence', models.CharField(blank=True, max_length=10, verbose_name='confidence')),
                ('judged', models.BooleanField(default=False, verbose_name='judgement available')),
                ('page_title', models.CharField(blank=True, max_length=300, verbose_name='page title')),
                ('page_description', models.TextField(blank=True, verbose_name='meta description')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='content hash')),
                ('page_bytes', models.PositiveIntegerField(default=0, verbose_name='page bytes')),
                ('elapsed_ms', models.FloatField(default=0.0, verbose_name='fetch time (ms)')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='fetched at')),
                ('prompt_pin', models.CharField(blank=True, max_length=100, verbose_name='prompt version')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_audits', to='organizations.organization', verbose_name='requested by organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_audits', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'website audit',
                'verbose_name_plural': 'website audits',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['url', '-created_at'], name='wsaudit_url_created_idx'), models.Index(fields=['organization', '-created_at'], name='wsaudit_org_created_idx')],
            },
        ),
    ]
