# Generated by Django 6.0.9 on 2026-10-09 09:12

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.CharField(blank=True, help_text='Where this came from, e.g. website_crawl, csv_import, provider:acme.', max_length=100, verbose_name='source')),
                ('source_url', models.URLField(blank=True, max_length=2048, verbose_name='source URL')),
                ('collected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='collected at')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='last verified at')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='confidence')),
                ('usage_license', models.CharField(blank=True, help_text='Terms this data may be used under, where a provider imposes any.', max_length=100, verbose_name='usage licence')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('full_name', models.CharField(blank=True, max_length=300, verbose_name='full name')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='job title')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='department')),
                ('seniority', models.CharField(blank=True, choices=[('individual', 'Individual contributor'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'VP'), ('c_level', 'C-level'), ('founder', 'Founder / Owner')], max_length=16, verbose_name='seniority')),
                ('is_decision_maker', models.BooleanField(default=False, verbose_name='decision maker')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('email_status', models.CharField(choices=[('unknown', 'Unknown'), ('verified', 'Verified'), ('risky', 'Risky'), ('invalid', 'Invalid'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='unknown', max_length=16, verbose_name='email status')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email verified at')),
                ('email_source', models.CharField(blank=True, max_length=100, verbose_name='email source')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('phone_status', models.CharField(choices=[('unknown', 'Unknown'), ('verified', 'Verified'), ('risky', 'Risky'), ('invalid', 'Invalid'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='unknown', max_length=16, verbose_name='phone status')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='phone verified at')),
                ('phone_source', models.CharField(blank=True, max_length=100, verbose_name='phone source')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='companies.company', verbose_name='company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['last_name', 'first_name', 'id'],
                'indexes': [models.Index(fields=['organization', 'company'], name='person_org_company_idx'), models.Index(fields=['organization', 'email_status'], name='person_org_emailstatus_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('organization', 'email'), name='one_person_per_email_per_org')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
