# Generated by Django 6.0.9 on 2026-10-08 10:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('feature', models.CharField(db_index=True, help_text='Which product capability ran this.', max_length=64, verbose_name='feature')),
                ('prompt_name', models.CharField(blank=True, max_length=100, verbose_name='prompt')),
                ('prompt_version', models.PositiveIntegerField(default=0, verbose_name='prompt version')),
                ('provider', models.CharField(blank=True, max_length=40, verbose_name='provider')),
                ('model_id', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('tier', models.CharField(blank=True, max_length=20, verbose_name='tier')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('invalid_output', 'Invalid output'), ('refused', 'Refused by model'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('error_reason', models.CharField(blank=True, max_length=255, verbose_name='error reason')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='input tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='output tokens')),
                ('cache_read_tokens', models.IntegerField(default=0, verbose_name='cache read tokens')),
                ('cache_write_tokens', models.IntegerField(default=0, verbose_name='cache write tokens')),
                ('cost_micro_usd', models.BigIntegerField(default=0, help_text='Millionths of a USD, so sub-cent calls are not rounded to zero.', verbose_name='cost (micro USD)')),
                ('latency_ms', models.FloatField(blank=True, null=True, verbose_name='latency ms')),
                ('output', models.JSONField(blank=True, default=dict, verbose_name='output')),
                ('subject_type', models.CharField(blank=True, max_length=100, verbose_name='subject type')),
                ('subject_id', models.CharField(blank=True, max_length=64, verbose_name='subject id')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
                ('usage_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='billing.usagerecord')),
            ],
            options={
                'verbose_name': 'AI job',
                'verbose_name_plural': 'AI jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='aijob_org_created_idx'), models.Index(fields=['organization', 'feature'], name='aijob_org_feature_idx'), models.Index(fields=['subject_type', 'subject_id'], name='aijob_subject_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
