# Generated by Django 6.0.9 on 2026-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='reasoning_tokens',
            field=models.IntegerField(default=0, verbose_name='reasoning tokens'),
        ),
    ]
