# Generated by Django 6.0.9 on 2026-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aijob_reasoning_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='guardrails_version',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='guardrails version'),
        ),
    ]
