# Generated by Django 6.0.9 on 2026-10-08 07:54

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('mfa_enabled', 'MFA enabled'), ('mfa_disabled', 'MFA disabled'), ('organization_created', 'Organization created'), ('organization_updated', 'Organization updated'), ('organization_deleted', 'Organization deleted'), ('workspace_created', 'Workspace created'), ('workspace_deleted', 'Workspace deleted'), ('member_invited', 'Member invited'), ('member_joined', 'Member joined'), ('member_removed', 'Member removed'), ('role_changed', 'Role changed'), ('apikey_created', 'API key created'), ('apikey_revoked', 'API key revoked'), ('integration_created', 'Integration created'), ('campaign_launched', 'Campaign launched'), ('campaign_paused', 'Campaign paused'), ('autopilot_enabled', 'AI autopilot enabled'), ('data_exported', 'Data exported'), ('data_deleted', 'Data deleted'), ('billing_changed', 'Billing changed'), ('compliance_changed', 'Compliance settings changed')], max_length=64, verbose_name='action')),
                ('actor_email', models.EmailField(blank=True, max_length=254, verbose_name='actor email')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='target type')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='target id')),
                ('target_label', models.CharField(blank=True, max_length=255, verbose_name='target label')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='user agent')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='request id')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'), models.Index(fields=['organization', 'action'], name='audit_org_action_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
