# Generated by Django 6.0.9 on 2026-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('mfa_enabled', 'MFA enabled'), ('mfa_disabled', 'MFA disabled'), ('organization_created', 'Organization created'), ('organization_updated', 'Organization updated'), ('organization_deleted', 'Organization deleted'), ('workspace_created', 'Workspace created'), ('workspace_deleted', 'Workspace deleted'), ('member_invited', 'Member invited'), ('member_joined', 'Member joined'), ('member_removed', 'Member removed'), ('role_changed', 'Role changed'), ('apikey_created', 'API key created'), ('apikey_revoked', 'API key revoked'), ('integration_created', 'Integration created'), ('company_profile_analyzed', 'Company profile analyzed'), ('company_profile_updated', 'Company profile edited'), ('company_profile_confirmed', 'Company profile confirmed'), ('icp_generated', 'ICP generated'), ('icp_updated', 'ICP edited'), ('icp_activated', 'ICP made active'), ('markets_recommended', 'Markets recommended'), ('markets_selected', 'Markets selected'), ('leads_imported', 'Leads imported'), ('signal_dismissed', 'Buying signal dismissed'), ('scoring_weights_changed', 'Scoring weights changed'), ('suppression_added', 'Suppression added'), ('suppression_removed', 'Suppression removed'), ('data_erased', 'Personal data erased'), ('consent_recorded', 'Consent recorded'), ('campaign_launched', 'Campaign launched'), ('campaign_paused', 'Campaign paused'), ('autopilot_enabled', 'AI autopilot enabled'), ('data_exported', 'Data exported'), ('data_deleted', 'Data deleted'), ('billing_changed', 'Billing changed'), ('compliance_changed', 'Compliance settings changed')], max_length=64, verbose_name='action'),
        ),
    ]
