# Generated by Django 6.0.9 on 2026-10-08 07:54

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('agency', 'Agency'), ('enterprise', 'Enterprise')], max_length=32, unique=True, verbose_name='tier')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('monthly_price_minor', models.BigIntegerField(default=0, verbose_name='monthly price (minor units)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('included_credits', models.IntegerField(default=0, verbose_name='included monthly credits')),
                ('max_seats', models.IntegerField(blank=True, null=True, verbose_name='max seats')),
                ('max_workspaces', models.IntegerField(blank=True, null=True, verbose_name='max workspaces')),
                ('max_prospects_per_month', models.IntegerField(blank=True, null=True, verbose_name='max prospects per month')),
                ('is_public', models.BooleanField(default=True, verbose_name='publicly selectable')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['sort_order', 'monthly_price_minor'],
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.IntegerField(help_text='Positive to grant credits, negative to consume them.', verbose_name='amount')),
                ('reason', models.CharField(choices=[('plan_allowance', 'Monthly plan allowance'), ('purchase', 'Credit purchase'), ('adjustment', 'Manual adjustment'), ('refund', 'Refund'), ('consumption', 'Consumption'), ('expiry', 'Expiry')], max_length=32, verbose_name='reason')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('feature', models.CharField(blank=True, max_length=64, verbose_name='feature')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='reference')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'credit entry',
                'verbose_name_plural': 'credit ledger',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='credit_org_created_idx'), models.Index(fields=['organization', 'feature'], name='credit_org_feature_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='trialing', max_length=32, verbose_name='status')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('manual', 'Manual / invoice')], default='manual', max_length=32, verbose_name='provider')),
                ('provider_customer_id', models.CharField(blank=True, max_length=200, verbose_name='provider customer id')),
                ('provider_subscription_id', models.CharField(blank=True, max_length=200, verbose_name='provider subscription id')),
                ('seats', models.IntegerField(default=1, verbose_name='seats')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='period start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='period end')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='trial ends at')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='canceled at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('organization',), name='subscription_one_live_per_org')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('metric', models.CharField(db_index=True, max_length=64, verbose_name='metric')),
                ('quantity', models.BigIntegerField(default=0, verbose_name='quantity')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='unit')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('input_tokens', models.BigIntegerField(default=0, verbose_name='input tokens')),
                ('output_tokens', models.BigIntegerField(default=0, verbose_name='output tokens')),
                ('estimated_cost_minor', models.BigIntegerField(default=0, verbose_name='estimated cost (minor units)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='occurred at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usage record',
                'verbose_name_plural': 'usage records',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'metric', '-occurred_at'], name='usage_org_metric_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
