# Generated by Django 6.0.9 on 2026-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('bachs', 'Bachs'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('manual', 'Manual / invoice')], default='manual', max_length=32, verbose_name='provider'),
        ),
    ]
