# Generated by Django 6.0.9 on 2026-10-09 09:12

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.CharField(blank=True, help_text='Where this came from, e.g. website_crawl, csv_import, provider:acme.', max_length=100, verbose_name='source')),
                ('source_url', models.URLField(blank=True, max_length=2048, verbose_name='source URL')),
                ('collected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='collected at')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='last verified at')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='confidence')),
                ('usage_license', models.CharField(blank=True, help_text='Terms this data may be used under, where a provider imposes any.', max_length=100, verbose_name='usage licence')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='legal name')),
                ('website', models.URLField(blank=True, max_length=2048, verbose_name='website')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='domain')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='industry')),
                ('sub_industry', models.CharField(blank=True, max_length=120, verbose_name='sub-industry')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='region')),
                ('employee_range', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=16, verbose_name='employee range')),
                ('revenue_range', models.CharField(blank=True, max_length=60, verbose_name='revenue range')),
                ('business_model', models.CharField(blank=True, max_length=120, verbose_name='business model')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='founded')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='public phone')),
                ('emails', models.JSONField(blank=True, default=list, verbose_name='public emails')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('social_links', models.JSONField(blank=True, default=list, verbose_name='social links')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disqualified', 'Disqualified'), ('duplicate', 'Merged into another record'), ('closed', 'No longer trading')], default='active', max_length=16, verbose_name='status')),
                ('enriched_at', models.DateTimeField(blank=True, null=True, verbose_name='last enriched')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='companies.company', verbose_name='merged into')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name', 'id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.CharField(blank=True, help_text='Where this came from, e.g. website_crawl, csv_import, provider:acme.', max_length=100, verbose_name='source')),
                ('source_url', models.URLField(blank=True, max_length=2048, verbose_name='source URL')),
                ('collected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='collected at')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='last verified at')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='confidence')),
                ('usage_license', models.CharField(blank=True, help_text='Terms this data may be used under, where a provider imposes any.', max_length=100, verbose_name='usage licence')),
                ('event_type', models.CharField(db_index=True, max_length=40, verbose_name='type')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='occurred at')),
                ('url', models.URLField(blank=True, max_length=2048, verbose_name='link')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.company', verbose_name='company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'company event',
                'verbose_name_plural': 'company events',
                'ordering': ['-occurred_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.CharField(blank=True, help_text='Where this came from, e.g. website_crawl, csv_import, provider:acme.', max_length=100, verbose_name='source')),
                ('source_url', models.URLField(blank=True, max_length=2048, verbose_name='source URL')),
                ('collected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='collected at')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='last verified at')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='confidence')),
                ('usage_license', models.CharField(blank=True, help_text='Terms this data may be used under, where a provider imposes any.', max_length=100, verbose_name='usage licence')),
                ('name', models.CharField(max_length=120, verbose_name='technology')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='category')),
                ('first_seen', models.DateTimeField(blank=True, null=True, verbose_name='first seen')),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last seen')),
                ('is_current', models.BooleanField(default=True, verbose_name='currently in use')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='companies.company', verbose_name='company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'company technology',
                'verbose_name_plural': 'company technologies',
                'ordering': ['company_id', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'country'], name='company_org_country_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'industry'], name='company_org_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'status'], name='company_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', ''), _negated=True), fields=('organization', 'domain'), name='one_company_per_domain_per_org'),
        ),
        migrations.AddIndex(
            model_name='companyevent',
            index=models.Index(fields=['organization', 'event_type', '-occurred_at'], name='event_org_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='companytechnology',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='one_technology_row_per_company'),
        ),
    ]
