# Generated by Django 6.0.9 on 2026-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='one_company_per_domain_per_org',
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('domain', ''), _negated=True), models.Q(('status', 'duplicate'), _negated=True)), fields=('organization', 'domain'), name='one_active_company_per_domain_per_org'),
        ),
    ]
