# Generated by Django 6.0.9 on 2026-10-09 15:53

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_search_indexes'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('filters', models.JSONField(default=dict, verbose_name='filters')),
                ('is_shared', models.BooleanField(default=False, verbose_name='shared with the workspace')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='last run')),
                ('last_result_count', models.PositiveIntegerField(default=0, verbose_name='last result count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'saved search',
                'verbose_name_plural': 'saved searches',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='one_saved_search_name_per_org')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
