# Generated by Django 6.0.9 on 2026-10-09 16:21

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_savedsearch'),
        ('intelligence', '0004_countryprofile_marketrecommendation'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.CharField(blank=True, help_text='Where this came from, e.g. website_crawl, csv_import, provider:acme.', max_length=100, verbose_name='source')),
                ('source_url', models.URLField(blank=True, max_length=2048, verbose_name='source URL')),
                ('collected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='collected at')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='last verified at')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='confidence')),
                ('usage_license', models.CharField(blank=True, help_text='Terms this data may be used under, where a provider imposes any.', max_length=100, verbose_name='usage licence')),
                ('signal_type', models.CharField(choices=[('funding', 'Funding'), ('hiring', 'Hiring'), ('expansion', 'Expansion'), ('acquisition', 'Acquisition'), ('new_office', 'New office'), ('leadership_change', 'Leadership change'), ('new_pages', 'New pages'), ('product_launch', 'Product launch'), ('pricing_change', 'Pricing change'), ('technology_change', 'Technology change'), ('website_change', 'Website change'), ('advertising', 'Advertising'), ('content_growth', 'Content growth'), ('social_activity', 'Social activity'), ('procurement', 'Procurement'), ('other', 'Other')], db_index=True, max_length=40, verbose_name='type')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('detector', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='detector')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='fingerprint')),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='occurred at')),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='first detected')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last confirmed')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('strength', models.PositiveSmallIntegerField(default=50, verbose_name='strength')),
                ('evidence', models.JSONField(blank=True, default=list, verbose_name='evidence')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='dismissed at')),
                ('dismiss_reason', models.CharField(blank=True, max_length=255, verbose_name='dismiss reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='companies.company', verbose_name='company')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_signals', to=settings.AUTH_USER_MODEL, verbose_name='dismissed by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='companies.companyevent', verbose_name='source event')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='intelligence.websitesnapshot', verbose_name='source snapshot')),
            ],
            options={
                'verbose_name': 'lead signal',
                'verbose_name_plural': 'lead signals',
                'ordering': ['-detected_at', '-id'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['organization', 'signal_type', '-detected_at'], name='signal_org_type_date_idx'), models.Index(fields=['organization', 'expires_at'], name='signal_org_expiry_idx'), models.Index(fields=['company', '-detected_at'], name='signal_company_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'signal_type', 'fingerprint'), name='one_signal_per_company_type_fingerprint'), models.CheckConstraint(condition=models.Q(('strength__gte', 0), ('strength__lte', 100)), name='signal_strength_is_a_percentage')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
