# Generated by Django 6.0.9 on 2026-10-09 09:12

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0001_initial'),
        ('intelligence', '0004_countryprofile_marketrecommendation'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('kind', models.CharField(choices=[('website_crawl', 'Website crawl'), ('import', 'File import'), ('provider', 'Licensed data provider'), ('manual', 'Added by hand'), ('api', 'Public API'), ('integration', 'CRM integration')], max_length=20, verbose_name='kind')),
                ('usage_license', models.CharField(blank=True, max_length=200, verbose_name='usage licence')),
                ('legal_review_at', models.DateTimeField(blank=True, null=True, verbose_name='legally reviewed at')),
                ('license_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='licence expires')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'lead source',
                'verbose_name_plural': 'lead sources',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('new', 'New'), ('researching', 'Researching'), ('qualified', 'Qualified'), ('enrolled', 'In a campaign'), ('engaged', 'Replied'), ('disqualified', 'Disqualified'), ('suppressed', 'Suppressed')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('score', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='opportunity score')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='score breakdown')),
                ('scored_at', models.DateTimeField(blank=True, null=True, verbose_name='scored at')),
                ('disqualified_reason', models.CharField(blank=True, max_length=255, verbose_name='disqualified because')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='first seen')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='last activity')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company', verbose_name='company')),
                ('icp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='intelligence.icp', verbose_name='matched ICP')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='contacts.person', verbose_name='primary contact')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-score', '-created_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='leadsource',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='one_lead_source_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status', '-score'], name='lead_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', '-score'], name='lead_org_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('organization', 'company', 'icp'), name='one_lead_per_company_per_icp'),
        ),
    ]
