# Generated by Django 6.0.9 on 2026-10-09 09:44

import apps.leads.import_models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_countryprofile_marketrecommendation'),
        ('leads', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(max_length=400, upload_to=apps.leads.import_models.import_upload_path, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='content type')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size')),
                ('status', models.CharField(choices=[('pending', 'Uploaded, awaiting column mapping'), ('ready', 'Mapped, ready to run'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16, verbose_name='status')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='column mapping')),
                ('detected_headers', models.JSONField(blank=True, default=list, verbose_name='detected headers')),
                ('sample_rows', models.JSONField(blank=True, default=list, verbose_name='sample rows')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='rows')),
                ('companies_created', models.PositiveIntegerField(default=0, verbose_name='companies created')),
                ('companies_updated', models.PositiveIntegerField(default=0, verbose_name='companies updated')),
                ('people_created', models.PositiveIntegerField(default=0, verbose_name='people created')),
                ('people_updated', models.PositiveIntegerField(default=0, verbose_name='people updated')),
                ('leads_created', models.PositiveIntegerField(default=0, verbose_name='leads created')),
                ('rows_skipped', models.PositiveIntegerField(default=0, verbose_name='rows skipped')),
                ('rows_failed', models.PositiveIntegerField(default=0, verbose_name='rows failed')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='errors')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='error')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('icp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='intelligence.icp', verbose_name='assign to ICP')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='leads.leadsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'import job',
                'verbose_name_plural': 'import jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='import_org_status_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
