# Generated by Django 6.0.9 on 2026-10-09 19:04

import apps.leads.scoring_models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_importjob'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weights', models.JSONField(default=apps.leads.scoring_models.default_weights, verbose_name='weights')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_profile_edits', to=settings.AUTH_USER_MODEL, verbose_name='last changed by')),
            ],
            options={
                'verbose_name': 'scoring profile',
                'verbose_name_plural': 'scoring profiles',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('organization',), name='one_scoring_profile_per_organization')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
