# Generated by Django 6.0.9 on 2026-10-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='onboarding completed at'),
        ),
    ]
