# Generated by Django 6.0.9 on 2026-10-10 15:33

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0002_organization_onboarding_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('law', models.CharField(blank=True, max_length=200, verbose_name='data protection law')),
                ('b2b_requires_prior_consent', models.BooleanField(default=True, verbose_name='B2B email needs prior consent')),
                ('opt_out_required', models.BooleanField(default=True, verbose_name='every message needs an opt-out')),
                ('sender_identity_required', models.BooleanField(default=True, verbose_name='sender must be identified')),
                ('postal_address_required', models.BooleanField(default=False, verbose_name='postal address in footer')),
                ('opt_out_honoured_within_days', models.PositiveSmallIntegerField(default=0, verbose_name='opt-out honoured within (days)')),
                ('max_retention_days', models.PositiveIntegerField(default=0, verbose_name='retention limit (days)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'regional policy',
                'verbose_name_plural': 'regional policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('value_hash', models.CharField(db_index=True, max_length=64, verbose_name='address hash')),
                ('value', models.CharField(blank=True, max_length=320, verbose_name='address')),
                ('basis', models.CharField(choices=[('consent', 'They opted in'), ('legitimate_interest', 'Legitimate interest (B2B)'), ('contract', 'Existing contract or relationship'), ('public_record', 'Published business contact details')], max_length=24, verbose_name='basis')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='source')),
                ('evidence', models.TextField(blank=True, help_text='What would be shown if asked: the form, the page, the contract.', verbose_name='evidence')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='captured at')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='withdrawn at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='contacts.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'consent record',
                'verbose_name_plural': 'consent records',
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'value_hash'], name='consent_org_hash_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SuppressionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('email', 'Email address'), ('phone', 'Phone number'), ('domain', 'Domain')], default='email', max_length=10, verbose_name='kind')),
                ('value_hash', models.CharField(db_index=True, max_length=64, verbose_name='value hash')),
                ('value', models.CharField(blank=True, max_length=320, verbose_name='value')),
                ('scope', models.CharField(choices=[('all', 'Every channel'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('call', 'Calls')], default='all', max_length=10, verbose_name='scope')),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed'), ('complained', 'Marked as spam'), ('bounced', 'Hard bounce'), ('manual', 'Added by hand'), ('imported', 'Imported suppression list'), ('legal_request', 'Legal or erasure request')], default='unsubscribed', max_length=20, verbose_name='reason')),
                ('source', models.CharField(blank=True, help_text='Where it came from: unsubscribe_link, webhook:ses, import, api.', max_length=120, verbose_name='source')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('suppressed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='suppressed at')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='evidence')),
                ('redacted_at', models.DateTimeField(blank=True, null=True, verbose_name='redacted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressions_created', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressions', to='contacts.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'suppression entry',
                'verbose_name_plural': 'suppression entries',
                'ordering': ['-suppressed_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'value_hash', 'scope'], name='supp_org_hash_scope_idx'), models.Index(fields=['organization', 'reason'], name='supp_org_reason_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind', 'value_hash', 'scope'), name='one_suppression_per_value_and_scope')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
